# -*- coding: utf-8 -*-


DATA_REPORT = '12'
SET_REPORT = '52'
CONTINUOUS_REPORTING = '04'
INTERMITTENT_REPORTING = '00'

REPORT_COREBUTTONS = '30'
REPORT_COREBUTTONS_ACC = '31'
REPORT_COREBUTTONS_ACC_EXT8 = '32'
REPORT_COREBUTTONS_ACC_IR = '33'
REPORT_COREBUTTONS_EXT19 = '34'
REPORT_COREBUTTONS_ACC_EXT16 = '35'
REPORT_COREBUTTONS_IR_EXT9 = '36'
REPORT_COREBUTTONS_ACC_IR_EXT6 = '37'
REPORT_EXT21 = '3d'
REPORT_COREBUTTONS_ACC_IR_INTERLEAVED = '3e'

COMMAND_REPORT_STATUS = '1500'
COMMAND_RUMBLE = '11%x1'
COMMAND_UNRUMBLE = '11%x0'
COMMAND_SET_LED = '11%x0'
